In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.drop('sales',axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
X.shape

(200, 3)

In [9]:
poly_features.shape # 19 column are the new features generated by polynomial regression of degree 3

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
# Now scale the data
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()

In [14]:
# fitting the scaler to only training set to avoid the data leakage scenario
scaler.fit(X_train)

StandardScaler()

In [15]:
# new scaled data
X_train = scaler.transform(X_train)

In [16]:
X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

# Ridge regression

In [18]:
from sklearn.linear_model import Ridge

In [19]:
# help(Ridge)

In [20]:
ridge_model = Ridge(alpha=10)

In [21]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [22]:
test_predictions = ridge_model.predict(X_test)

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [24]:
MAE = mean_absolute_error(y_test,test_predictions)

In [25]:
MAE

0.5774404204714173

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [27]:
RMSE

0.8946386461319676

In [28]:
from sklearn.linear_model import RidgeCV
# RidgeCV performs a variety of cross validation for a multiple alpha values and report backs the best alpha value

In [29]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10),scoring='neg_mean_absolute_error')

In [30]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [31]:
ridge_cv_model.alpha_
# To check the best possible value of alpha

0.1

In [32]:
from sklearn.metrics import SCORERS

In [33]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [34]:
test_predictions = ridge_cv_model.predict(X_test)

In [35]:
MAE = mean_absolute_error(y_test,test_predictions)

In [36]:
MAE

0.4273774884353493

In [37]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [38]:
RMSE

0.6180719926954669

In [39]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

## LASSO - least absolute shrinkage and selection operator

In [42]:
# first step is to check for a suitable alpha value

In [43]:
from sklearn.linear_model import LassoCV

In [49]:
lasso_cv_model = LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=100000)

In [50]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=100000)

In [51]:
 lasso_cv_model.alpha_

0.004943070909225827

In [52]:
 test_predictions = lasso_cv_model.predict(X_test)

In [53]:
MAE = mean_absolute_error(y_test,test_predictions)

In [54]:
MAE

0.43350346185900673

In [55]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [56]:
RMSE

0.6063140748984032

In [57]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])