In [1]:
import numpy as np

To make 1-D arrays from list, we can use np.array() function

In [2]:
mylist = [1,3,4]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 3, 4])

To permanently store the obtained array we need to make use of an variable

In [5]:
arr = np.array(mylist)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 3, 4])

To make 2-D arrays from nested list, we can use np.array() function

In [8]:
list2 = [[2,3,4],[4,6,7],[7,9,6]]

In [9]:
list2

[[2, 3, 4], [4, 6, 7], [7, 9, 6]]

In [10]:
mat = np.array(list2)

In [11]:
mat

array([[2, 3, 4],
       [4, 6, 7],
       [7, 9, 6]])

In [12]:
type(mat)

numpy.ndarray

We can create arrays directly by using np.arange(start,end,step) function. The resulting array will not include the end 

In [13]:
np.arange(0,23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In the above code 23 is not included because the by-default step size is 1 so it stopped at 22

In [14]:
np.arange(0,23,5)

array([ 0,  5, 10, 15, 20])

In the above code 23 is not included bcoz after 20 the next element would be 25 which would breach the end, hence it stopped at 20

If we want to create matrix of zeros and ones we can use np.zeros((row,col)) and np.ones((row,col))

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

The above method is used to make array of row=1 & col=0

In [16]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Another way to create arrays is by using the     np.linspace(start,end,num_of_elem) method. In this end is also included in the resultant array

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In the above code the 0 5 10 have equal difference between them

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

If the num_of_elem is not odd number the resultant array is quite difficult to read as shown in the above code

To create an identity matrix we can use np.eye() method

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Different ways to create an array and populate it with random values from a distribution

1. np.random.rand(row,col) :
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)`` where 0 is inclusive and 1 is exclusive

In [22]:
np.random.rand(3,4)

array([[0.55911701, 0.08934455, 0.27638165, 0.12469961],
       [0.08045225, 0.72124609, 0.53991358, 0.94396565],
       [0.75922375, 0.39930657, 0.56256447, 0.8935326 ]])

2. np.random.rand(row,col) : Create an array of the given shape and populate it with the random samples from a standard normal distribution. It inlcudes both pos+ and neg- numbers. The chance of getting the number close to zero is higher.

In [23]:
np.random.randn()

-0.31704589405833905

In [24]:
np.random.randn(5)

array([-0.85751887, -0.46285685, -1.6672634 ,  0.03532028,  0.23981304])

In [25]:
np.random.randn(3,4)

array([[-0.91436172, -1.48229506,  1.45538468, -0.71242743],
       [ 0.8459499 ,  1.00650901, -0.01491819, -1.08998066],
       [-0.22887667, -0.2827388 ,  1.02771083, -0.57404316]])

3. np.random.randint(start,end,num_of_ele) : Returns an array having random elements between start and end equal to num_of_ele 

In [38]:
np.random.randint(0,30,20)

array([28,  7, 10, 20, 24,  7,  6, 14,  9, 20, 18, 23,  7,  7, 15, 12,  0,
       20, 10, 12])

In [27]:
np.random.randint(0,101,(3,4))

array([[ 8, 59,  1, 39],
       [22, 21, 85, 41],
       [95, 71, 28, 72]])

We can get the random  integers in the form of matrix by defining the row & col in place of num_of_ele

4. np.random.seed(any_num) : This function makes the any_num a pointer that holds a particular set of random numbers 
which would remain same once always for that any_num

In [28]:
np.random.seed(43)
np.random.rand(4)

array([0.11505457, 0.60906654, 0.13339096, 0.24058962])

If you again run the above code u would get the same result

In [29]:
np.random.seed(43)
np.random.rand(4)

array([0.11505457, 0.60906654, 0.13339096, 0.24058962])

Some attributes of the above methods:

1. reshape(row,col) : To convert the array in the matrix form

In [46]:
arr2 = np.arange(0,21)

In [49]:
arr2.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

The product of the row and col should be equal to the total number of elements in the array

2. max() : To get the maximum element from the array

In [51]:
randarr = np.random.randint(0,101,10)

In [52]:
randarr

array([35, 50, 75, 89, 65, 34, 75, 66, 99,  4])

In [53]:
randarr.max()

99

2. min() : To get the minimum element from the array

In [55]:
randarr.min()

4

3. argmax() : To get the index of maximum element from the array

In [56]:
randarr.argmax()

8

4. argmin() : To get the index of minimum element from the array

In [58]:
randarr.argmin()

9

5. dtype : To check the data type of the array

In [60]:
randarr.dtype

dtype('int32')

6. shape : To check the shape of the array

In [63]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [64]:
arr2.shape

(21,)

In [68]:
arr3 = arr2.reshape(3,7)

In [69]:
arr3.shape

(3, 7)

For grabbing single and mulitple element from an arrray use this,

In [8]:
myarr = np.arange(11)

In [9]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
myarr[6]

6

In [14]:
myarr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
myarr[:5]

array([0, 1, 2, 3, 4])

In [15]:
myarr[5:]

array([ 5,  6,  7,  8,  9, 10])

For broadcasting an element in the array use this,

In [16]:
myarr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
myarr[0:4] = 33

In [18]:
myarr

array([33, 33, 33, 33,  4,  5,  6,  7,  8,  9, 10])

For slicing elements from the array use this method,

In [19]:
ary = np.arange(0,11)

In [20]:
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_ary = ary[0:4]

In [22]:
slice_of_ary

array([0, 1, 2, 3])

In [23]:
slice_of_ary[:] = 33

In [24]:
slice_of_ary

array([33, 33, 33, 33])

In [25]:
ary

array([33, 33, 33, 33,  4,  5,  6,  7,  8,  9, 10])

As seen in above code the slicing points towards the elements of the array and doesn't store its copy, hence any changes made to the sliced array will affect the original array. 


To avoid this issue, create an copy of the original array using .copy() method and perform all the required actions on it.

In [26]:
ary_copy = ary.copy()

In [27]:
ary_copy

array([33, 33, 33, 33,  4,  5,  6,  7,  8,  9, 10])

To grab an element from the 2-D array use array[row][col] or array[row,col]

In [29]:
arr_2d = np.array([[23,45,32],[12,65,73],[33,55,76]])

In [30]:
arr_2d

array([[23, 45, 32],
       [12, 65, 73],
       [33, 55, 76]])

In [31]:
arr_2d[1][1]

65

In [32]:
arr_2d[1,1]

65

In [33]:
arr_2d[:2,1:]

array([[45, 32],
       [65, 73]])

Above code displays the row 0 and 1 || col 1 and 2

Filtering the array using the comparison operators,

In [34]:
arr = np.arange(1,11)

In [35]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [37]:
bool_arr = arr>4

In [38]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In the above code, we are only displaying the elements that are True in bool_arr

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

Operations on array

In [50]:
arr = np.arange(0,11)

In [51]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [53]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
arr/arr

C:\Users\aalam\AppData\Local\Temp\ipykernel_23260\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In the above code, 0/0 gives a not a number(nan)

In [58]:
1/arr

C:\Users\aalam\AppData\Local\Temp\ipykernel_23260\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In the above code, 1/0 gives infinity

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [60]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [61]:
np.log(arr)

C:\Users\aalam\AppData\Local\Temp\ipykernel_23260\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [62]:
arr.sum()

55

In [63]:
arr.mean()

5.0

In [64]:
arr.max()

10

In [65]:
arr.min()

0

In [66]:
arr.var()

10.0

In [67]:
arr.std()

3.1622776601683795

In [68]:
arr2d = np.arange(0,25).reshape(5,5)

In [69]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
arr2d.sum()

300

In [71]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In the above code, axis=0 means perform the operation across the col

In [73]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In the above code, axis=1 means perform the operation across the row